### ISSUE TITLE
Save files directory when "always ask" is selected?

### ISSUE THREAD

**Issue by clampak** [dogpixels/patreon-helper#2]
Where does this save the files when the when Firefox is set to always ask where to save downloads?

**Comment by dogpixels** [comment]
Good question! I ran a few tests and figured out that Firefox apparently remembers the last configured download directory and uses that for background downloads, even though you've set the Browser to always ask.

**Comment by dogpixels** [comment]
CLosing this issue, since there's nothing more to do about it. Feel free to reopen if necessary.
