### ISSUE TITLE
Request feature - Externalize download interval variable

### ISSUE THREAD

**Issue by Lowell13** [dogpixels/patreon-helper#3]
Hello there,

I'd like to request a feature : I saw in your code that you're using a variable to store the download interval, which is used to reduce the load on patreon server. I'm not sure this one is used (or I'm bad enough with JS to not notice it), but do you think you could make it available to changes through the preferences tab in extensions page ?
The point is that, currently, your extension is perfectly suitable to a normal usage (pictures, music for example). Problem is that I also use it to download heavier stuff, like .psd which are around 100mo+. It messes up the stuff, since the download doesn't finishes in time to get added to the database. It causes me various problem : either the file is download again and stored into the Download folder specified by the browser and not the extension, or next files get tagged as "_unknwon" even if the first one of the post was found. That's the two main behaviour that I saw. Sometimes I got both because why not.

P.S. : Thanks a bunch for this extension, honestly it helps A LOT !

**Comment by dogpixels** [comment]
Hey there! You were right, the variable was never used. I've changed that, and with the new version 1.13 that should roll out via AMO very soon, you'll now find a download interval configuration in the settings tab. Let me know if it works as intended. Cheers!

**Comment by Lowell13** [comment]
Hello there !

Thanks a lot, it indeed work very well ! :) Sadly, that didn't fixed my issue... I don't really get why, so I'll send you a mail with logs in a few minutes. I'll close this issue since the feature is implemented, don't hesitate to tell me if you want me to open a new one for the mail I'm sending you.
